### ISSUE TITLE
Let's use Yarn instead of NPM for installing dependencies

### ISSUE THREAD

**Issue by lohanidamodar** [Cedware/electron-angular-toolkit#2]
Lets us update to use Yarn package manager instead of Npm for installing electron dependencies while running prepare command

**Comment by Cedware** [comment]
I've never heard about yarn, can you just describe whats the problem with npm and why you think yarn will work better?

**Comment by lohanidamodar** [comment]
https://yarnpkg.com/en/
This should answer your queries.
Let's just say, yarn is npm on steroids...

**Comment by Kaffiend** [comment]
no reason to not support both.

**Comment by Cedware** [comment]
I think so to, npm is the default package manager and I don't think there is the need to support yarn with this project
