### ISSUE TITLE
NPM package old executable file

### ISSUE THREAD

**Issue by lohanidamodar** [Cedware/electron-angular-toolkit#3]
When i install electron-angular-toolkit from npm, i get the updated source code but the executable file
node_modules/.bin/electron-angular-toolkit is still old using same old 'angular-cli' and 'angular-cli.json' instead of updated '@angular/cli' and '.angular-cli.json'

# I think this error occurs because the function preparePacageJson() has error, there is no write statement to write package.json file, also no try block for catch block

**Comment by nitinkumarmishra** [comment]
not working with latest angular version.
![image](https://cloud.githubusercontent.com/assets/14124584/24708247/eda1871c-1a33-11e7-8d04-4d40812244f7.png)

**Comment by lohanidamodar** [comment]
yes, i have submitted the pull request solving the problem, but the developer has not been able to merge..so the problem exist.
You can however checkout my fork for the solution that works
https://github.com/lohanitech/electron-angular-toolkit

**Comment by Cedware** [comment]
I'm gonna merge and test your fix tomoorow evening;)

**Comment by emolr** [comment]
Actually the master branch is already pointing to `@angular/cli` it seems like it's just needs to be recompiled and published to npm
