### ISSUE TITLE
packager documentation & configuration

### ISSUE THREAD

**Issue by Kaffiend** [Cedware/electron-angular-toolkit#8]
update documentation to reflect additional requirements of packaging with native modules.

repro
install mongodb to use within electron
implement it in angular service/component etc.

explanation
mongodb requires the `resolve-from` package so we need to add it to the `nativeModules` declaration in the package.json but you also have to add `resolve-from` to your dependencies and the nativeModules array since the peer dependencies are not included so a mention of the possibility of additional dependencies of the nativemodule need to be added.

also may need a declaration of custom dependencies, such as custom dlls, exe etc... 
example would be, the app uses a scanner and for windows platform it utilizes the CLScan.exe to call the TWAIN driver. To include that in the packaging from a configurable source of external dependencies would be awesome.

**Comment by Cedware** [comment]
Alright I'm confused if mongodb relies on require-from and resolve-from, why aren't they a part of the mongodbs dependencies?

**Comment by Kaffiend** [comment]
just `resolve-from sorry, typo.

I am asking myself the same question.
in development just building its fine just declaring it a `nativeModule`

but package throws error
npm install failed.] - normalizeTree: sill install loadCurrentTree
packages: mongodb@^2.2.25, resolve-from@undefined
{ Error: No compatible version found: resolve-from@undefined
Valid install targets:
1.0.0, 1.0.1, 2.0.0
```
    at pickVersionFromRegistryDocument (D:\appl\card-file\node_modules\npm\lib\fetch-package-metadata.js:161:16)
    at D:\appl\card-file\node_modules\npm\node_modules\iferr\index.js:13:50
    at D:\appl\card-file\node_modules\npm\lib\utils\pulse-till-done.js:20:8
    at saved (D:\appl\card-file\node_modules\npm\lib\cache\caching-client.js:174:7)
    at D:\appl\card-file\node_modules\npm\node_modules\graceful-fs\polyfills.js:261:18
    at FSReqWrap.oncomplete (fs.js:123:15) code: 'ETARGET' }
```

**Comment by Kaffiend** [comment]
instead of an array of names can we just declare them like normal dependencies with versioning in the `nativeModules` object?
update [this](https://github.com/Cedware/electron-angular-toolkit/blob/master/src/index.ts#L234) to go by the properties instead of each entry and install explicitly with version?

**Comment by Cedware** [comment]
'resolve-from@undefined' <- This seems to be an electron-angular-toolkit problem.
Anyway it could be necessary to add peer dependencies of a native module into nativeModules to prevent the dependency getting bundled, which would destroy some c-binding I think

**Comment by Cedware** [comment]
Your suggestion should solve the problem ;)

**Comment by Kaffiend** [comment]
closing in favor of the milestone. The external deps included in the package is an entire different aspect and deserves its own issue
