### ISSUE TITLE
Problem with installing native dependencies (version: undefined)

### ISSUE THREAD

**Issue by Cedware** [Cedware/electron-angular-toolkit#9]
> just resolve-from sorry, typo.
> 
> I am asking myself the same question.
> in development just building its fine just declaring it a nativeModule
> 
> but package throws error
> npm install failed.] - normalizeTree: sill install loadCurrentTree
> packages: mongodb@^2.2.25, resolve-from@undefined
> { Error: No compatible version found: resolve-from@undefined
> Valid install targets:
> 1.0.0, 1.0.1, 2.0.0
> 
>     at pickVersionFromRegistryDocument (D:\appl\card-file\node_modules\npm\lib\fetch-package-metadata.js:161:16)
>     at D:\appl\card-file\node_modules\npm\node_modules\iferr\index.js:13:50
>     at D:\appl\card-file\node_modules\npm\lib\utils\pulse-till-done.js:20:8
>     at saved (D:\appl\card-file\node_modules\npm\lib\cache\caching-client.js:174:7)
>     at D:\appl\card-file\node_modules\npm\node_modules\graceful-fs\polyfills.js:261:18
>     at FSReqWrap.oncomplete (fs.js:123:15) code: 'ETARGET' }
> looks to me like a peer dependency issue on the mongodb lib, chock it up to a workaround with adding it to package.json until they fix it?

**Comment by Cedware** [comment]
@Kaffiend, I took a close look at the problem, this is how things a working at the moment:
**installNativeDependenciesIntoBuild** takes each dependency which is mentioned in **nativeModules** and takes the corresponding version from the **dependencies** section.
This works well as long you are not defining any per dependencies as native, because the will not be found at the **dependencies**.
So I think there are two possibilities:
1. You have to specify the versions twice, once at the **dependencies* section and once at the **nativeDependencies** section
2. nativeModules will contain a simple list of strings, like it is at the moment, and **installNativeDependenciesIntoBuild** will take the correct version from **dependencies**. If the package isn't listed as dependency the package will not be installed explicit but it will be installed as per-dependency automatically as part of the dependency tree.

At the moment I'm not sure which is the better solution, but I tend to prefer the second one

**Comment by Kaffiend** [comment]
that explains a lot.
Currently to get mongodb native into electron i have...
```
 "dependencies": {
  ...
    "mongodb": "^2.2.25",
    "resolve-from": "2.0.0",
  ... 
  },
 "nativeModules": [
    "mongodb",
    "resolve-from"
  ]
```
this works, just took a minute to figure out what was happening and how to get it to know what version to install into the build.

**Comment by Cedware** [comment]
You'll  still have to provide "resolve-from" as nativeModule - Actually I have no solution for that issue. It would be necessary to analyze the whole dependency tree and figure out which packages uses some native stuff.

But after implementing the second solution you wold not have to add resolve-from to the dependency list.
To be clear, your package.json will look like this:
```
 "dependencies": {
  ...
    "mongodb": "^2.2.25"
  ... 
  },
 "nativeModules": [
    "mongodb",
    "resolve-from"
  ]
```

**Comment by Kaffiend** [comment]
thats feels like the cleaner solution, i dont much like the adding of native peer modules to dependencies just for that. This feels more contained within the lib, retains lib specifics in the same lib specific package.json setting.

**Comment by Kaffiend** [comment]
at least this way, you can chase errors for the peer native modules to add ;P
